export enum AccountType {
  CASH = 'CASH',
  BANK = 'BANK',
  CREDIT_CARD = 'CREDIT_CARD',
  DEBIT_CARD = 'DEBIT_CARD',
  SAVINGS = 'SAVINGS',
  INVESTMENT = 'INVESTMENT',
  LOAN = 'LOAN',
  DIGITAL_WALLET = 'DIGITAL_WALLET',
}